"""Phase 1: initial schema per ADR-0016

Revision ID: 31ddf610b741
Revises: 
Create Date: 2026-09-10 05:41:54.645460

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '31ddf610b741'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category')),
    sa.UniqueConstraint('name', name=op.f('uq_category_name'))
    )
    op.create_table('invoice_counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('next_sequence', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_counter'))
    )
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permission')),
    sa.UniqueConstraint('code', name=op.f('uq_permission_code'))
    )
    op.create_table('setting',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_setting'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('initials', sa.String(length=8), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone_raw', sa.String(length=32), nullable=True),
    sa.Column('phone_normalised', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('credit_limit_paisa', sa.Integer(), nullable=True),
    sa.Column('credit_terms_days', sa.Integer(), nullable=True),
    sa.Column('balance_paisa', sa.Integer(), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_verified_at', sa.DateTime(), nullable=True),
    sa.Column('phone_verified_method', sa.String(length=16), nullable=True),
    sa.Column('phone_verified_by_user_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['phone_verified_by_user_id'], ['user.id'], name=op.f('fk_customer_phone_verified_by_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer'))
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('unit_label', sa.String(length=32), nullable=False),
    sa.Column('allows_fractional', sa.Boolean(), nullable=False),
    sa.Column('cost_price_paisa', sa.Integer(), nullable=True),
    sa.Column('sell_price_paisa', sa.Integer(), nullable=False),
    sa.Column('stock_quantity_milli', sa.Integer(), nullable=False),
    sa.Column('low_stock_threshold_milli', sa.Integer(), nullable=True),
    sa.Column('is_provisional', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('cost_price_paisa IS NULL OR cost_price_paisa >= 0', name=op.f('ck_product_cost_price_non_negative')),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_product_name_not_blank')),
    sa.CheckConstraint('sell_price_paisa >= 0', name=op.f('ck_product_sell_price_non_negative')),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_product_category_id_category')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], name=op.f('fk_product_created_by_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product')),
    sa.UniqueConstraint('sku', name=op.f('uq_product_sku'))
    )
    op.create_table('role_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], name=op.f('fk_role_permission_permission_id_permission')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_permission')),
    sa.UniqueConstraint('role', 'permission_id', name='role_permission_unique')
    )
    op.create_table('notification_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=24), nullable=False),
    sa.Column('dedupe_key', sa.String(length=120), nullable=False),
    sa.Column('payload_json', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_notification_queue_customer_id_customer')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_queue')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_notification_queue_dedupe_key'))
    )
    op.create_table('product_barcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.Column('price_override_paisa', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], name=op.f('fk_product_barcode_created_by_user_id_user')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_product_barcode_product_id_product')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_barcode')),
    sa.UniqueConstraint('barcode', name=op.f('uq_product_barcode_barcode'))
    )
    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('terminal_label', sa.String(length=32), nullable=True),
    sa.Column('subtotal_paisa', sa.Integer(), nullable=False),
    sa.Column('discount_paisa', sa.Integer(), nullable=False),
    sa.Column('tax_paisa', sa.Integer(), nullable=False),
    sa.Column('total_paisa', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=16), nullable=False),
    sa.Column('amount_tendered_paisa', sa.Integer(), nullable=True),
    sa.Column('change_paisa', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_sale_customer_id_customer')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_sale_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sale')),
    sa.UniqueConstraint('invoice_number', name=op.f('uq_sale_invoice_number'))
    )
    op.create_table('stock_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=16), nullable=False),
    sa.Column('quantity_delta_milli', sa.Integer(), nullable=False),
    sa.Column('quantity_before_milli', sa.Integer(), nullable=False),
    sa.Column('quantity_after_milli', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('reference_type', sa.String(length=32), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('length(trim(reason)) > 0', name=op.f('ck_stock_movement_reason_not_blank')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], name=op.f('fk_stock_movement_created_by_user_id_user')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_stock_movement_product_id_product')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_movement'))
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('amount_paisa', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('received_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_payment_customer_id_customer')),
    sa.ForeignKeyConstraint(['received_by_user_id'], ['user.id'], name=op.f('fk_payment_received_by_user_id_user')),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], name=op.f('fk_payment_sale_id_sale')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment'))
    )
    op.create_table('sale_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_barcode_id', sa.Integer(), nullable=True),
    sa.Column('product_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('unit_price_paisa_snapshot', sa.Integer(), nullable=False),
    sa.Column('quantity_milli', sa.Integer(), nullable=False),
    sa.Column('quantity_source', sa.String(length=16), nullable=False),
    sa.Column('line_discount_paisa', sa.Integer(), nullable=False),
    sa.Column('line_total_paisa', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_barcode_id'], ['product_barcode.id'], name=op.f('fk_sale_item_product_barcode_id_product_barcode')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_sale_item_product_id_product')),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], name=op.f('fk_sale_item_sale_id_sale')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sale_item'))
    )
    op.create_table('credit_ledger_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.String(length=16), nullable=False),
    sa.Column('amount_paisa', sa.Integer(), nullable=False),
    sa.Column('balance_after_paisa', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('override_authorised_by_user_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], name=op.f('fk_credit_ledger_entry_created_by_user_id_user')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_credit_ledger_entry_customer_id_customer')),
    sa.ForeignKeyConstraint(['override_authorised_by_user_id'], ['user.id'], name=op.f('fk_credit_ledger_entry_override_authorised_by_user_id_user')),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], name=op.f('fk_credit_ledger_entry_payment_id_payment')),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], name=op.f('fk_credit_ledger_entry_sale_id_sale')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_ledger_entry'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit_ledger_entry')
    op.drop_table('sale_item')
    op.drop_table('payment')
    op.drop_table('stock_movement')
    op.drop_table('sale')
    op.drop_table('product_barcode')
    op.drop_table('notification_queue')
    op.drop_table('role_permission')
    op.drop_table('product')
    op.drop_table('customer')
    op.drop_table('user')
    op.drop_table('setting')
    op.drop_table('permission')
    op.drop_table('invoice_counter')
    op.drop_table('category')
    # ### end Alembic commands ###
