"""Phase 3: refund and refund_item per ADR-0020

Revision ID: 58f3a01f76d8
Revises: 31ddf610b741
Create Date: 2026-09-11 04:29:06.995778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58f3a01f76d8'
down_revision = '31ddf610b741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refund',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('total_paisa', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('initiated_by_user_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('length(trim(reason)) > 0', name=op.f('ck_refund_reason_not_blank')),
    sa.CheckConstraint('total_paisa >= 0', name=op.f('ck_refund_total_non_negative')),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['user.id'], name=op.f('fk_refund_approved_by_user_id_user')),
    sa.ForeignKeyConstraint(['initiated_by_user_id'], ['user.id'], name=op.f('fk_refund_initiated_by_user_id_user')),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], name=op.f('fk_refund_sale_id_sale')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refund'))
    )
    op.create_table('refund_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refund_id', sa.Integer(), nullable=False),
    sa.Column('sale_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity_milli', sa.Integer(), nullable=False),
    sa.Column('line_total_paisa', sa.Integer(), nullable=False),
    sa.Column('restock', sa.Boolean(), nullable=False),
    sa.CheckConstraint('quantity_milli > 0', name=op.f('ck_refund_item_quantity_positive')),
    sa.ForeignKeyConstraint(['refund_id'], ['refund.id'], name=op.f('fk_refund_item_refund_id_refund')),
    sa.ForeignKeyConstraint(['sale_item_id'], ['sale_item.id'], name=op.f('fk_refund_item_sale_item_id_sale_item')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refund_item'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refund_item')
    op.drop_table('refund')
    # ### end Alembic commands ###
