"""Phase 5: WhatsApp consent, message counter, statement runs per ADR-0028 and ADR-0033

Existing customers migrate as NOT opted in (server default 0) — agreement is never
assumed retroactively (ADR-0028 §2). notification_queue.customer_id becomes nullable
for an Admin's test send, which has no customer (ADR-0033 §10).

Revision ID: de48cca91869
Revises: 58f3a01f76d8
Create Date: 2026-09-15 00:59:26.647734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de48cca91869'
down_revision = '58f3a01f76d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_daily_count',
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('sent', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('day', name=op.f('pk_message_daily_count'))
    )
    op.create_table('statement_run',
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('queued_at', sa.DateTime(), nullable=True),
    sa.Column('skipped_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('month', name=op.f('pk_statement_run'))
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp_opt_in', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('whatsapp_opt_in_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_opt_in_by_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_customer_whatsapp_opt_in_by_user_id_user'), 'user', ['whatsapp_opt_in_by_user_id'], ['id'])

    with op.batch_alter_table('notification_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_message_id', sa.String(length=128), nullable=True))
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # test sends have no customer and can't survive customer_id becoming NOT NULL again
    op.execute("DELETE FROM notification_queue WHERE customer_id IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_queue', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('provider_message_id')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_customer_whatsapp_opt_in_by_user_id_user'), type_='foreignkey')
        batch_op.drop_column('whatsapp_opt_in_by_user_id')
        batch_op.drop_column('whatsapp_opt_in_at')
        batch_op.drop_column('whatsapp_opt_in')

    op.drop_table('statement_run')
    op.drop_table('message_daily_count')
    # ### end Alembic commands ###
